import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Card from "../components/card";
import styles from "../styles/index.module.css";

import {
  faFacebookF,
  faTwitter,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";
export default function Home() {
  const cards = [
    {
      title: "Grow Together",
      body: `Generate meaningful discussions with our audience anc
      build a strong. oval communitv. Think of the insightfu
      conversations you miss out on with a feedback form.`,
      imgSrc: "/img/illustration-grow-together.svg",
      css: "md:flex-row-reverse",
    },
    {
      title: "Flowing Conversations",
      body: `You wollan a conversaton In so wny
      it online? Our threads have just-in-time loading
      5 tor a mor
      natural flow.`,
      imgSrc: "/img/illustration-flowing-conversation.svg",
      css: " ",
    },
    {
      title: "Your Users",
      body: `It takes no time at all to integrate Huddle with your app .
      authentcation solution. Ins means, once signed In (c
      vour ado. vour users can start chatting immediately.`,
      imgSrc: "/img/illustration-your-users.svg",
      css: "md:flex-row-reverse",
    },
  ];

  return (
    <div>
      <Head>
        <title>Huddle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon-32x32.png" />
      </Head>
      {/* header */}
      <header
        className={`${styles.header} m-0 p-4 md:px-16 md:py-12 bg-dark-cyen`}
      >
        <div className="flex justify-between items-center">
          <div className="relative w-24 h-4 md:w-48 md:h-8">
            <Image src="/img/logo.svg" alt="logo" layout="fill" />
          </div>

          <button className="bg-white capitalize py-1 px-7 md:px-14  md:py-3 rounded-full shadow-xl text-sm font-bold">
            try it free
          </button>
        </div>
        <div className="md:flex md:justify-between md:items-center mt-c-75">
          <div className="mr-5 text-center md:text-left">
            <p className="text-3xl capitalize font-bold">Build The community</p>
            <p className="text-3xl capitalize font-bold mt-3">
              your fans will love
            </p>
            <p className="mt-6 font-thin">
              Huddle re-imagines the way we build communities. You have a voice,
              but so does your audience. Create connections with your users as
              you engage in genuine discussion.
            </p>
            <button className="mt-8 bg-c-pink px-14 py-4 text-white text-sm font-bold rounded-full capitalize">
              get started for free
            </button>
          </div>
          <div className="text-center mt-16 md:mt-0">
            <div className="relative w-[100%] md:w-[800px] md:h-[550px]">
              <img src="/img/illustration-mockups.svg" alt="mockup" />
            </div>
          </div>
        </div>
      </header>

      {/* main section */}

      <div className="container mx-auto px-5">
        {cards.map((card, index) => (
          <Card key={index} card={card} />
        ))}
      </div>

      {/* footer */}
      <div className="bg-dark-cyan text-white md:p-20 text-thin text-sm relative mt-10">
        {/* <div className="w-full py-10 md:px-20 shadow-2xl bg-white absolute text-center rounded-lg -top-2/4 translate-y-1/4 left-2/4 -translate-x-2/4">
          <p className="text-black text-xl font-bold">
            Ready To Build Your Community?
          </p>
          <button className="mt-6 bg-c-pink px-14 py-4 text-white text-sm font-bold rounded-full capitalize">
            get started for free
          </button>
        </div> */}
        {/* <Image src="/img/logo.svg" layout="fill" alt="logo" className="text-white"/> */}
        <div className="grid md:grid-cols-3 justify-items-center mt-12 p-5 gap-5">
          <div className="flex flex-col gap-5 mr-10">
            <div className="flex gap-4">
              <div>
                <Image
                  src="/img/icon-location.svg"
                  width="50px"
                  height="50px"
                  alt="locationIcon"
                />
              </div>
              <p>
                orem insum dolor sit amer. consecterul adiniscing alit sed do
                ellismod temnor incididunt ut labore et dolore magna aliqua
              </p>
            </div>
            <div className="flex justify-start items-center text-white text-thin gap-4">
              <Image
                src="/img/icon-phone.svg"
                width="20px"
                height="20px"
                alt="phoneIcon"
              />
              <p>+1-543-123-4567</p>
            </div>
            <div className="flex justify-start items-center text-white text-thin gap-4">
              <Image
                src="/img/icon-email.svg"
                width="20px"
                height="20px"
                alt="emailIcon"
              />
              <p>example@huddle.com</p>
            </div>
          </div>
          <div className="flex flex-col md:flex-row place-self-stretch justify-around gap-4">
            <div className="">
              <ul className="flex flex-col gap-4">
                {[
                  {
                    title: "about us",
                    link: "#",
                  },
                  {
                    title: "what we do",
                    link: "#",
                  },
                  {
                    title: "FAQ",
                    link: "#",
                  },
                ].map((item, index) => (
                  <li key={index}>
                    <Link href={item.link}>
                      <a className="capitalize my-8">{item.title}</a>
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <ul className="flex flex-col gap-4">
                <li>
                  <Link href="#">
                    <a>Career</a>
                  </Link>
                </li>
                <li>
                  <Link href="#">
                    <a>Blog</a>
                  </Link>
                </li>
                <li>
                  <Link href="#">
                    <a>contact us</a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="flex gap-3">
            {[faFacebookF, faTwitter, faInstagram].map((item, index) => (
              <FontAwesomeIcon
                key={index}
                icon={item}
                className="h-6 w-6 border rounded-full p-1"
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
